name: Trigger Docs Update

permissions: {}

on:
  release:
    types: [published]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger docs update workflow
        run: |
          repo="stacklok/docs-website"
          event_type="published-release"
          version="${{ github.event.release.tag_name }}"

          echo "Triggering docs update for $repo with version $version"
